paths:
  input:
    npi_jsonl: ./sample_data/npi/npi_sample.jsonl
    internal_jsonl: ./sample_data/internal/internal_sample.jsonl
  working:
    bronze_npi: ./_work/bronze_npi_raw.parquet
    bronze_internal: ./_work/bronze_internal_raw.parquet
    silver_providers: ./_work/providers_normalized.parquet
    silver_sites: ./_work/sites_normalized.parquet
    silver_xref: ./_work/provider_site_link.parquet
  output:
    gold_providers: ./_output/gold_canonical_providers.parquet
    gold_sites: ./_output/gold_canonical_sites.parquet
    gold_xref: ./_output/gold_provider_site_xref.parquet
    gold_view: ./_output/gold_hcp_view.parquet

run:
  build_id: local-demo-001
